language: go
os: linux

# fuse on travis
sudo: required
dist: bionic # Ubuntu 18.04 "Bionic", https://docs.travis-ci.com/user/reference/bionic/

env:
  - GO111MODULE=on

git:
  depth: 300

# Build with the lastest relevant Go versions
# Relevance is determined from:
# * https://golang.org/dl/
# * https://packages.debian.org/search?keywords=golang&searchon=names&exact=1&suite=all&section=all
# * https://packages.ubuntu.com/search?keywords=golang&searchon=names&exact=1&suite=all&section=all
go:
  - 1.11.x # Debian 10 "Buster"
  - 1.12.x # Ubuntu 19.10
  - 1.13.x # Debian 11 "Bullseye"
  - stable

before_install:
  - sudo apt-get install -qq fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

script:
  - openssl version
  - df -Th / /tmp
  - env GO111MODULE=on go build
  - ./build-without-openssl.bash
  - ./build.bash
  - ./gocryptfs -speed
  - ./test.bash
  - make root_test
  - ./crossbuild.bash
  - echo "rebuild with locked dependencies"
  - go mod vendor
  - ./build.bash -mod=vendor
